export type FileRelationType =
  | "belongsTo"
  | "hasOne"
  | "belongsToMany"
  | "hasMany"
  | "belongsToArray";

export type FileFieldDescriptor = {
  // Business collection that owns the file relation field, e.g. "users".
  sourceCollection: string;
  // Relation field on the business collection, e.g. "avatar".
  fieldName: string;
  // Target file-template collection from the relation field's `target`, e.g. "files".
  fileCollection: string;
  dataSourceKey?: string;
  // Relation type from the business field's `type`.
  relation: FileRelationType;
  /**
   * @deprecated Multiplicity is derived from relation. Keep this only for
   * backward-compatible descriptors generated by older templates.
   */
  multiple?: boolean;
  accept?: string | string[];
  maxSize?: number;
};

export type StorageUploadRules = {
  size?: number;
  mimetype?: string | string[];
};

export type FileStorageInfo = {
  id: string | number;
  name: string;
  title?: string;
  type: string;
  rules?: StorageUploadRules;
  // Newer NocoBase versions may expose this capability from storages:check.
  clientUpload?: boolean;
};

export type StorageCheckResult = {
  isSupportToUploadFiles: boolean;
  storage: FileStorageInfo;
};

export type NocoBaseFileRecord = {
  id: string | number;
  title?: string;
  filename: string;
  extname?: string;
  size?: number;
  mimetype?: string;
  path?: string;
  url?: string;
  preview?: string;
  storageId?: string | number;
  meta?: Record<string, unknown>;
};

export type FileUploadFieldValue =
  | NocoBaseFileRecord
  | NocoBaseFileRecord[]
  | null;

export type SerializedFileFieldValue =
  | { id: string | number }
  | Array<{ id: string | number }>
  | null;

export type FileUploadOptions = {
  file: File;
  descriptor: FileFieldDescriptor;
  storage: FileStorageInfo;
  signal?: AbortSignal;
};

export type FileUploadMode = "auto" | "direct" | "multipart";

export type FileUploadHandlerOptions = {
  file: File;
  descriptor: FileFieldDescriptor;
  signal?: AbortSignal;
};

export type FileUploadHandler = (
  options: FileUploadHandlerOptions
) => Promise<NocoBaseFileRecord>;

export type FileUploadItem = {
  key: string;
  rawFile?: File;
  displayName: string;
  showStatus?: boolean;
  status:
    | "pending"
    | "checking"
    | "uploading"
    | "done"
    | "error"
    | "cancelled";
  record?: NocoBaseFileRecord;
  error?: Error;
};

export type FileUploadMessages = {
  chooseFiles: string;
  chooseFile: string;
  dragActive: string;
  dragInactive: string;
  checkingStorage: string;
  uploading: string;
  uploaded: string;
  failed: string;
  cancelled: string;
  retry: string;
  remove: string;
  cancel: string;
  storageUnsupported: string;
  maxFilesReached: string;
  uploadDisabled: string;
  noFiles: string;
  fileSizeExceeded: (maxSize: number) => string;
  storageMimeTypeRejected: string;
  fieldMimeTypeRejected: string;
  directUploadFailed: (status: number) => string;
  uploadInProgress: string;
  uploadFailedValidation: string;
};

export type FilePreviewMessages = {
  preview: string;
  download: string;
  previous: string;
  next: string;
  close: string;
  noFiles: string;
  unsupportedTitle: string;
  unsupportedDescription: string;
  imageAlt: (filename: string) => string;
  pdfTitle: string;
  textTitle: string;
  audioTitle: string;
  videoTitle: string;
  officeTitle: string;
  officeLoading: string;
  officeError: string;
};
